### ISSUE TITLE
Add https://marumari.github.io/crypto-presentation as URL to the top of the GitHub repo

### ISSUE THREAD

**Issue by lgarron** [marumari/crypto-presentation#14]

**Comment by april** [comment]
Like in the README.md file?

**Comment by april** [comment]
Okay, it's right there at the top.  :)  Thanks!

**Comment by lgarron** [comment]
Uh, I mean the top of the repo, not the `README`, e.g. like `http://timer.cubing.net` at the top of https://github.com/cubing/timer

(But README is also useful.)

**Comment by april** [comment]
Oh, duh!  Sorry, it's been a _really_ long last couple days.  Should definitely be done now.  :)

**Comment by lgarron** [comment]
Yay! :-D
