### ISSUE TITLE
Proposal for diagram on slide 110

### ISSUE THREAD

**Issue by ttaubert** [marumari/crypto-presentation#7]
Trying to imitate the target audience, I think that the simplified crypto system would confused me for a second as I don't immediately understand that the ciphertext _and_ the hash are transmitted to Bob. Would visually separating those two transfers make that clearer?

<img width="1125" alt="screen shot 2015-12-05 at 05 22 29" src="https://cloud.githubusercontent.com/assets/300895/11606004/e9bee0ca-9b10-11e5-876c-f09d5df3b79e.png">

**Comment by april** [comment]
This was an awesome piece of feedback!  I redid all 7 of the digital signature images in 36cc13be90fcbc2b272e8a182960506bebee9684.

Of course, I shall always see them with red squiggly lines.  :)
